### ISSUE TITLE
deploy.sh doesn't find "Loadbalancer" string on my Centos 7

### ISSUE THREAD

**Issue by dieselsteve** [keptn/jenkins-service#18]
Hi all,
    
`kubectl describe svc istio-ingressgateway -n istio-system | grep "LoadBalancer Ingress:"`

doesn't work on my System because of the following:

`kubectl describe svc istio-ingressgateway -n istio-system | grep -e IP -e Type`
`Type:                     LoadBalancer`
`IP:                       10.102.191.200`

so I need to change the line like follows to get it to work:

`kubectl describe svc istio-ingressgateway -n istio-system | grep "IP:" | sed 's~IP:[ \t]*~~'`

Is that a bug on my side?

rgds Steve

**Comment by jetzlstorfer** [comment]
Hi Steve,
I am assuming you are referring to the command to get the IP of the gateway here: https://github.com/keptn/jenkins-service/blob/release-0.2.x/deploy.sh#L16 

In the command you mentioned the last part is missing, the original command is:
`kubectl describe svc istio-ingressgateway -n istio-system | grep "LoadBalancer Ingress:" | sed 's~LoadBalancer Ingress:[ \t]*~~'`
The script relies on the public IP of the gateway, which means that your change to use the internal IP would not work unfortunately.

**Comment by dieselsteve** [comment]
Hi Jürgen,

I see... So no public IP no service...

many thanks for that fast answer!

rgds Steve
