### ISSUE TITLE
--retry-connrefused not quite commonly available for curl versions in the wild

### ISSUE THREAD

**Issue by akirasoft1** [keptn/jenkins-service#6]
It was released as part of 7.52, the dependency wouldn't be satisfied in Ubuntu releases until Bionic (18.04)

**Comment by jetzlstorfer** [comment]
thanks for mentioning this. @johannes-b do we need this additional option?

**Comment by johannes-b** [comment]
Mike, thanks for identifying this issue. 
Yes, we do have another (more generic) option. I will address it while working on: https://github.com/keptn/keptn/issues/259

**Comment by johannes-b** [comment]
The way to deal with --retry-connrefused issue is that a while loop captures failed curls for a couple of times. Please see following snippet: https://github.com/keptn/jenkins-service/blob/develop/deploy.sh#L47
